name: login_clevercost_1
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  syncfusion_flutter_charts: ^21.1.35
  water_drop_nav_bar: ^2.2.0+5
  font_awesome_flutter: ^10.4.0
  url_launcher: ^6.1.10
  email_validator: ^2.0.1
  flutter_svg: ^2.0.1
  dio: ^5.1.2
  get: ^4.6.5
  flutter_form_builder: ^9.0.0
  intl: ^0.18.1
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner: ^2.4.4
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.0
  

flutter:
  uses-material-design: true

  fonts:
    - family: Lato
      fonts:
        - asset: fonts/Lato-Regular.ttf
        - asset: fonts/Lato-Bold.ttf
          weight: 700

  assets:
    - lib/images/
    - lib/icons/
    - assets/
